version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres:14.1
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: users_db
    ports: 
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

  api:
    container_name: node_api
    build:
      context: ./firstServer
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    ports:
      - '8000:8000'
    volumes:
      - ./firstServer/src:/app/src

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./rabbitmq/data/:/var/lib/rabbitmq/
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 5

  mail:
    container_name: mail_api
    build:
      context: ./mailServer
      dockerfile: ./Dockerfile
    
    depends_on:
      - rabbitmq
    ports:
      - '9000:9000'
    volumes:
      - ./mailServer/:/app/
        
volumes:
  postgres:
  rabbitmq: